In [8]:
import sys, os
from pathlib import Path
sys.path.append(str(Path(os.path.dirname(os.path.abspath("__file__"))).parent))

In [17]:
%load_ext autoreload
%autoreload 2
%matplotlib inline
from inchworm_measurement.laser import Laser
from inchworm_measurement import utils
import numpy as np


The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [9]:
%load_ext autoreload
%autoreload 2
%matplotlib inline
from inchworm_measurement.laser import Laser
from inchworm_measurement import utils
import numpy as np

n = 6
spotlaser_origin = np.zeros((3, n))
spotlaser_direction = np.array(
    [[np.cos(i * np.pi / n * 2), np.sin(i * np.pi / n * 2), 1] for i in range(n)]
).T
spot_laser = Laser(spotlaser_origin, spotlaser_direction)


Laser.save(spot_laser, "test")

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [11]:
m = Laser.load("test")

In [4]:
spot_direction_three = np.array(
    [
        [-1, -1, -1],
        [0, 1, -1],
        [-1, 1, 1],
    ]
)
spot_direction_three = spot_direction_three / np.linalg.norm(spot_direction_three, axis=0)
print(spot_direction_three)


[[-0.70710678 -0.57735027 -0.57735027]
 [ 0.          0.57735027 -0.57735027]
 [-0.70710678  0.57735027  0.57735027]]


In [30]:
x = [1,2,3]
y = [0,1,2,3,4]
z = [y[i] for i in x]

In [4]:
x = {(-2500.0,), (2500.0,)}
print(list(x))

[(2500.0,), (-2500.0,)]


In [4]:
import numpy as np
np.all([True, False, True])

False

In [26]:
from operator import itemgetter
class O:
    pass
o = O()
o.p = 1
o.q = 2

p, q = o.p, o.q
print(p,q)

1 2


In [13]:
x = {"a": 1, "b": 2} 
a,b = x.keys()
print(a,b)

a b


In [18]:
x = 1
print(dict(["a", "b"], [1, 2]))

TypeError: dict expected at most 1 argument, got 2

In [11]:
is_camera_moved = [0,1,1,1,0,1,1,1,0]
section = []
group = [0]
for i in range(len(is_camera_moved)):
    if is_camera_moved[i]:
        group.append(i+1)
    else:
        section.append(group)
        group = [i+1]
if group:
    section.append(group)
    
print(section)

[[0], [1, 2, 3, 4], [5, 6, 7, 8], [9]]


In [18]:
section = []
group = []
separtor_idx = [ for i, is_moved in enumerate(is_camera_moved)]
print(separtor_idx)

SyntaxError: invalid syntax (745583819.py, line 3)

In [33]:
is_camera_moved = np.array(is_camera_moved)
all_idx = np.arange(len(is_camera_moved))
separtor_idx = all_idx[not is_camera_moved]+1
separtor_idx = [0, *separtor_idx ,len(is_camera_moved)+1]
section = []
for current, next in zip(separtor_idx[:-1], separtor_idx[1:]):
    section.append(np.arange(current, next))
    
print(section)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()