In [1]:
%load_ext autoreload
%autoreload 2
%matplotlib inline
from inchworm_measurement.laser import Laser
from inchworm_measurement import utils
import numpy as np

n = 6
spotlaser_origin = np.zeros((3, n))
spotlaser_direction = np.array(
    [[np.cos(i * np.pi / n * 2), np.sin(i * np.pi / n * 2), 1] for i in range(n)]
).T
spot_laser = Laser(spotlaser_origin, spotlaser_direction)


Laser.save(spot_laser, "test")

In [11]:
m = Laser.load("test")

In [4]:
spot_direction_three = np.array(
    [
        [-1, -1, -1],
        [0, 1, -1],
        [-1, 1, 1],
    ]
)
spot_direction_three = spot_direction_three / np.linalg.norm(spot_direction_three, axis=0)
print(spot_direction_three)


[[-0.70710678 -0.57735027 -0.57735027]
 [ 0.          0.57735027 -0.57735027]
 [-0.70710678  0.57735027  0.57735027]]


In [30]:
x = [1,2,3]
y = [0,1,2,3,4]
z = [y[i] for i in x]

In [4]:
x = {(-2500.0,), (2500.0,)}
print(list(x))

[(2500.0,), (-2500.0,)]


In [4]:
import numpy as np
np.all([True, False, True])

False

In [26]:
from operator import itemgetter
class O:
    pass
o = O()
o.p = 1
o.q = 2

p, q = o.p, o.q
print(p,q)

1 2


In [13]:
x = {"a": 1, "b": 2} 
a,b = x.keys()
print(a,b)

a b


In [18]:
x = 1
print(dict(["a", "b"], [1, 2]))

TypeError: dict expected at most 1 argument, got 2